const WORDS = [
  { id: "e", word: "e", pos: "Konjunktion",
    de: ["und"], en: ["and"],
    origin: "Italienisch 'e'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["e", "nɛe"] },
  ]}},
  { id: "ɪn", word: "ɪn", pos: "Präposition",
    de: ["in"], en: ["in"],
    origin: "Englisch 'in'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["ɪn", "nɛɪn"] },
  ]}},
  { id: "kɛ", word: "kɛ", pos: "Präposition",
    de: ["zu"], en: ["to"],
    origin: "Indonesisch 'ke'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["kɛ", "nɛkɛ"] },
  ]}},
  { id: "kon", word: "kon", pos: "Konjunktion",
    de: ["mit"], en: ["with"],
    origin: "Italienisch 'con'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["kon", "nɛkon"] },
  ]}},
  { id: "na", word: "na", pos: "Präposition",
    de: ["auf"], en: ["on"],
    origin: "Polnisch 'na'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["na", "nɛna"] },
  ]}},
  { id: "bɛ", word: "bɛ", pos: "Verb",
    de: ["sein"], en: ["be"],
    origin: "Englisch 'be'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Kein Partizip", cells: ["bɛ", "nɛbɛ"] },
      { label: "Partizip I", cells: ["bɛɔ", "nɛbɛɔ"] },
      { label: "Partizip II", cells: ["bɛɔn", "nɛbɛɔn"] },
  ]}},
  { id: "dla", word: "dla", pos: "Präposition",
    de: ["für"], en: ["for"],
    origin: "Russisch 'для'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["dla", "nɛdla"] },
  ]}},
  { id: "ɛs", word: "ɛs", pos: "Substantiv",
    de: ["er/sie/es"], en: ["he/she/it"],
    origin: "Deutsch 'es'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Nominativ Singular", cells: ["ɛs", "nɛɛs"] },
      { label: "Dativ Singular", cells: ["aɛs", "nɛaɛs"] },
      { label: "Nominativ Plural", cells: ["ɛsɛ", "nɛɛsɛ"] },
      { label: "Dativ Plural", cells: ["aɛsɛ", "nɛaɛsɛ"] },
  ]}},
  { id: "akɛ", word: "akɛ", pos: "Adjektiv",
    de: ["an"], en: ["on"],
    origin: "Italienisch 'acceso'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Basisform", cells: ["akɛ", "nɛakɛ"] },
      { label: "Komparativ", cells: ["akɛɪ", "nɛakɛɪ"] },
      { label: "Superlativ", cells: ["akɛu", "nɛakɛu"] },
  ]}},
  { id: "ad", word: "ad", pos: "Präposition",
    de: ["bei"], en: ["at"],
    origin: "Englisch 'at'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["ad", "nɛad"] },
  ]}},
  { id: "ave", word: "ave", pos: "Verb",
    de: ["haben"], en: ["have"],
    origin: "Italienisch 'avere'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Kein Partizip", cells: ["ave", "nɛave"] },
      { label: "Partizip I", cells: ["aveɔ", "nɛaveɔ"] },
      { label: "Partizip II", cells: ["aveɔn", "nɛaveɔn"] },
  ]}},
  { id: "jadɪ", word: "jadɪ", pos: "Verb",
    de: ["werden"], en: ["become"],
    origin: "Indonesisch 'menjadi'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Kein Partizip", cells: ["jadɪ", "nɛjadɪ"] },
      { label: "Partizip I", cells: ["jadɪɔ", "nɛjadɪɔ"] },
      { label: "Partizip II", cells: ["jadɪɔn", "nɛjadɪɔn"] },
  ]}},
  { id: "mele", word: "mele", pos: "Substantiv",
    de: ["sie (Plural)"], en: ["they (plural)"],
    origin: "Indonesisch 'mereka'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Nominativ Singular", cells: ["mele", "nɛmele"] },
      { label: "Dativ Singular", cells: ["amele", "nɛamele"] },
      { label: "Nominativ Plural", cells: ["meleɛ", "nɛmeleɛ"] },
      { label: "Dativ Plural", cells: ["ameleɛ", "nɛameleɛ"] },
  ]}},
  { id: "pɔ", word: "pɔ", pos: "Präposition",
    de: ["nach"], en: ["after"],
    origin: "Polnisch 'po'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["pɔ", "nɛpɔ"] },
  ]}},
  { id: "um", word: "um", pos: "Präposition",
    de: ["um"], en: ["in order to"],
    origin: "Deutsch 'um'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["um", "nɛum"] },
  ]}},
  { id: "gve", word: "gve", pos: "Partikel",
    de: ["Fragewort"], en: ["question word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Frage nach Substantiv", cells: ["gve", "nɛgve"] },
      { label: "Frage nach Verb", cells: ["gva", "nɛgva"] },
      { label: "Frage nach Adjektiv", cells: ["gvɛ", "nɛgvɛ"] },
      { label: "Frage nach Adverb", cells: ["gvɪ", "nɛgvɪ"] },
      { label: "Frage nach Präposition", cells: ["gvɔ", "nɛgvɔ"] },
      { label: "Frage nach Konjunktion", cells: ["gvu", "nɛgvu"] },
  ]}},
  { id: "psɛd", word: "psɛd", pos: "Präposition",
    de: ["vor (zeitlich)"], en: ["before"],
    origin: "Polnisch 'przed'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["psɛd", "nɛpsɛd"] },
  ]}},
  { id: "davan", word: "davan", pos: "Präposition",
    de: ["vor (räumlich)"], en: ["in front of"],
    origin: "Italienisch 'davanti'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["davan", "nɛdavan"] },
  ]}},
  { id: "sopa", word: "sopa", pos: "Präposition",
    de: ["über"], en: ["above"],
    origin: "Italienisch 'sopra'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["sopa", "nɛsopa"] },
  ]}},
  { id: "hɛ", word: "hɛ", pos: "Partikel",
    de: ["Ja-Nein-Fragewort"], en: ["yes/no question word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["hɛ", "nɛhɛ"] },
  ]}},
  { id: "no", word: "no", pos: "Konjunktion",
    de: ["aber"], en: ["but"],
    origin: "Russisch 'но'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["no", "nɛno"] },
  ]}},
  { id: "lɔp", word: "lɔp", pos: "Konjunktion",
    de: ["oder"], en: ["or"],
    origin: "Polnisch 'lub'.",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["lɔp", "nɛlɔp"] },
  ]}},
  { id: "ple", word: "ple", pos: "Partikel",
    de: ["Zeitformwort"], en: ["tense word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "Präteritum/Perfekt", cells: ["ple", "nɛple"] },
      { label: "Plusquamperfekt", cells: ["plo", "nɛplo"] },
      { label: "Futur I", cells: ["plɪ", "nɛplɪ"] },
      { label: "Futur II", cells: ["plu", "nɛplu"] },
  ]}},
  { id: "o", word: "o", pos: "Partikel",
    de: ["Relativsatzwort"], en: ["relative clause word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["o", "nɛo"] },
  ]}},
  { id: "ta", word: "ta", pos: "Partikel",
    de: ["Komplementsatzwort"], en: ["complement clause word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["ta", "nɛta"] },
  ]}},
  { id: "kɔ", word: "kɔ", pos: "Partikel",
    de: ["Konjunktivwort"], en: ["conjunctive word"],
    origin: "-",
    example: {
      conlang: "[Kommen später].",
      de: "[Kommen später]",
      en: "[Coming soon]",
    }, formsTable: { columns: ["", "positiv", "negativ"], rows: [
      { label: "-", cells: ["kɔ", "nɛkɔ"] },
  ]}},
];